version: 1.0.0

logging:
  level: "info"
  format: "console"

auth:
  timeout_in_ms: 3000

providers:
  - name: "ecmwf-api"
    type: "ecmwf-api"
    realm: "ecmwf"
    uri: "https://api.ecmwf.int/v1"
  - name: "plain-provider"
    type: "plain"
    realm: "localrealm"
    users:
      - username: "admin-user"
        password: "admin-pass"
      - username: "reader-user"
        password: "reader-pass"
      - username: "producer-user"
        password: "producer-pass"

augmenters:
  - name: "ecmwf-role-augmenter"
    type: "plain_advanced"
    realm: "ecmwf"
    match:
      username: ["<your-ecmwf-username>"]
    augment:
      roles: ["admin"]
  - name: "plain-role-augmenter"
    type: "plain"
    realm: "localrealm"
    roles:
      admin: ["admin-user"]
      reader: ["reader-user"]
      producer: ["producer-user"]

store:
  enabled: false

services: []

jwt:
  exp: 3600
  iss: "authotron-local"
  secret: "your-shared-secret"
  aud: "authotron-local"

bind_address: 0.0.0.0:8080
